
Метод	                                        Класс
kNN – k ближайших соседей	                    sklearn.neighbors.KNeighborsClassifier
LDA – линейный дискриминантный анализ           sklearn.lda.LDA
QDA – квадратичный дискриминантный анализ     	sklearn.qda.QDA
Logistic – логистическая регрессия	            sklearn.linear_model.LogisticRegression
SVC – машина опорных векторов	                sklearn.svm.SVC
Tree – деревья решений	                        sklearn.tree.DecisionTreeClassifier
RF – случайный лес                           	sklearn.ensemble.RandomForestClassifier
AdaBoost – адаптивный бустинг	                sklearn.ensemble.AdaBoostClassifier
GBT – градиентный бустинг деревьев решений	    sklearn.ensemble.GradientBoostingClassifier

Метод класса             	Описание
fit(X, y)	                обучение (тренировка) модели на обучающей выборке X, y
predict(X)	                предсказание на данных X
set_params(**params)      	установка параметров алгоритма
get_params()	            чтение параметров алгоритма

In [2]:
import pandas as pd

data = pd.read_csv('wine.csv',names = ['Grade', 'P1', 'P2', 'P3','P4','P5','P6','P7','P8','P9','P10','P11','P12','P13'], sep = ',')
data.head() # первые пять строк


Grade     P1    P2    P3    P4   P5    P6    P7    P8    P9   P10   P11  \
0      1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04   
1      1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05   
2      1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03   
3      1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86   
4      1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04   

    P12   P13  
0  3.92  1065  
1  3.40  1050  
2  3.17  1185  
3  3.45  1480  
4  2.93   735

In [14]:
import sklearn
X = data.values[::, 1:14] # Создаем массивы, где X — признаки (с 1 по 13 колонки), y — классы (0ая колонка). 
y = data.values[::, 0:1]
# функцией train_test_split из sklearn.cross_validation. разобьеn данные на обучающую/тестовую выборкb 60%:40%
import sklearn
from sklearn.model_selection import train_test_split as train
X_train, X_test, y_train, y_test = train(X, y, test_size=0.)

N_train, _ = X_train.shape 
N_test,  _ = X_test.shape 
print (N_train, N_test)

from sklearn.ensemble import RandomForestClassifier #случайный лес

clf = RandomForestClassifier(n_estimators=100, n_jobs=-1) # первый отвечает за количество деревьев в лесу, 2 -  (при -1 задействованы все ядра, по умолчанию стоит 1).
clf.fit(X_train, y_train) #обучаем
clf.score(X_test, y_test) #чтобы определить точность предсказанных




106 72


/home/vova/1cloud/1cloud/lib/python3.6/site-packages/ipykernel_launcher.py:16: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  app.launch_new_instance()


0.9583333333333334

In [18]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
y_train_predict = knn.predict(X_train)
y_test_predict = knn.predict(X_test)

err_train = np.mean(y_train != y_train_predict)
err_test  = np.mean(y_test  != y_test_predict)
print (err_train, err_test)

0.6632253470986116 0.6678240740740741


/home/vova/1cloud/1cloud/lib/python3.6/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


In [22]:
from sklearn.svm import SVC
svc = SVC()
svc.fit(X_train, y_train)

err_train = np.mean(y_train != svc.predict(X_train))
err_test  = np.mean(y_test  != svc.predict(X_test))
print (err_train, err_test)

0.6247775008899964 0.6423611111111112


/home/vova/1cloud/1cloud/lib/python3.6/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [23]:
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X, y)
print(model)
# make predictions
expected = y
predicted = model.predict(X)
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))


GaussianNB(priors=None, var_smoothing=1e-09)
              precision    recall  f1-score   support

         1.0       1.00      0.98      0.99        59
         2.0       0.99      0.99      0.99        71
         3.0       0.98      1.00      0.99        48

    accuracy                           0.99       178
   macro avg       0.99      0.99      0.99       178
weighted avg       0.99      0.99      0.99       178

[[58  1  0]
 [ 0 70  1]
 [ 0  0 48]]


/home/vova/1cloud/1cloud/lib/python3.6/site-packages/sklearn/naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


ImportError: cannot import name 'calculate_accuracy'